### PR TITLE
chore: Support `anyio<3` and `anyio>=4` 

### LINKED ISSUE #5: AttributeError: module 'anyio' has no attribute 'start_blocking_portal'
Using `anyio>=4.0.0` breaks:
```
  File "/home/grigi/work/magneto/.pyenv/lib64/python3.11/site-packages/starlette_testclient/_testclient.py", line 450, in _portal_factory
    with anyio.start_blocking_portal(**self.async_backend) as portal:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'anyio' has no attribute 'start_blocking_portal'
```
Downgrading to `anyio<4` resolves the issue.

### PR DESCRIPTION
**Pull request by Stranger6667**
Resolves #5

### CODE REVIEW

**Comment by Kludex** [comment]
Don't you want to test both versions? Old and new?

**Comment by Stranger6667** [comment]
Yep, probably the PR title is misleading - indeed, I'd like to support both versions

Re: tests - I went with a simpler option of downgrading `anyio` and re-running the tests in the same job

**Comment by Stranger6667** [comment]
All green! @Kludex let me know if you are ok with these changes

If everything is OK, then I'd be happy to issue a new release (now 100% sure how to make it though, assuming via manual workflow dispatch in `Actions`)

**Comment by Stranger6667** [comment]
Moving this forward, hopefully, we can resolve any potential concerns separately :)

**Comment by Stranger6667** [comment]
Oh, it looks something is wrong with credentials to PyPI, so the new release is not uploaded :(

**Comment by Kludex** [comment]
@Stranger6667 Can you give me your PyPI username? I'm going to give you access there as well.

**Comment by Stranger6667** [comment]
"Stranger6667", thanks!

**Comment by Kludex** [comment]
Done. Thanks! 🙏

**Pull request merged**
